### PR TITLE
add functionality for always notifying for certain pilots or channels

### PR DESCRIPTION
**Pull request by ghost**
* Add Always Notify section to Settings
* Add ability to always notify for certain pilots and/or channels
* Update some of the settings window labels for consistency in capitalization, etc. 
* Update some of the dependent package versions
* Fix indentation and whitespace in files edited.

### CODE REVIEW

**Comment by ghost** [comment]
@MyUncleSam: 

First of all, thank you so much for the work on this project! I have enjoyed the use of your app for some time. I sort of always wanted to have a feature of being able to notify for a specific person or channel. And in the last 2 years, I've been studying software development and have been working as a developer professionally for about 4 months now. 

I came back to Eve, and decided to give it a go. C# is not my native language, but one that I'm in the process of learning. 

I made the code changes to facilitate the overall feature enhancement but later realized the indentation was a bit off. So, I used a formatter on the files I edited. It seems that there were more than a trivial amount of changes. I'm not sure if you care to make those updates or not, but the key changes for the enhancement will be in [THIS](https://github.com/MyUncleSam/EveChatNotifier/pull/12/commits/7080717096f713d5da73c879d39e02fd4b5de612) commit

I wasn't sure about versioning the app, so I left that alone. I'm not sure if you're still active on here or not, so I'll give it some time. If I don't hear back from you, I'll build a release and post it on my forked github. 

Thanks again!

**Comment by ghost** [comment]
@MyUncleSam - Since I haven't heard back. I'm going to up the release version to 2.10.3.0 and zip up a release on my fork.

**Comment by MyUncleSam** [comment]
Hi @DigitalCraze,

I am sorry but the last few days I had no time to take a look into it. But I promise I do it this weekend.

**Review by MyUncleSam — APPROVED** [review]

**Comment by MyUncleSam** [comment]
@DigitalCraze thank you very much for your contribution. I reviewed your code and added it to the project.

Also some changes was made a friend of mine requested. These changes lead into a new version 2.10.3.0 which is live now. If you have the "Check For Updates" enabled you get a popup with the option to update.

(And the tray icon has a new menu item "Contributors" which now shows you too as contributor :-) )

**Comment by ghost** [comment]
@MyUncleSam - You have no idea how much you just made my day. I'm a self-taught python developer who just this last year got into a start-up for dev work and have been taking this stuff more seriously. I've been branching out with new languages and have been using your app for years. I decided to give it a go. This is actually my first-ever contribution. So this is a huge moment for me. Thank you. <3

**Pull request merged**
